### PR TITLE
Publish API docs in CI

### PR DESCRIPTION
**Pull request by funkymalc**
## Purpose
Publish API documentation 

## Approach
Add Publish API doc step in Jenkinsfile

### CODE REVIEW

**Comment by cowboyd** [comment]
Thanks @funkymalc! Will this pick up any `*.raml` file in the `/ramls` directory, or is that set by the config file that @dcrossleyau maintains?

**Comment by dcrossleyau** [comment]
At this time, the config needs to explicitly list each raml file. Job when i get back to office to enhance that. https://github.com/folio-org/folio-org.github.io/blob/master/_data/api.yml

**Comment by cowboyd** [comment]
That makes sense. 

So if we go ahead and merge this without any ramls, it won't break anything, and then once we add the top-level raml to repository, I can pass you the name of the file and we should be good to go?

**Comment by dcrossleyau** [comment]
I was expecting you to add your initial skeleton raml branch first, then this Jenkinsfile PR. The api.yml  config is already deployed with "eholdings.raml" as the first.

**Comment by dcrossleyau** [comment]
Any issues with the generation of API docs do not break the CI, just emit messages. So safe to merge in whatever order.

**Review by cowboyd — APPROVED** [review]

**Pull request merged**
