### PR TITLE
Move JSON rescue block to the bottom of the configuration update method

### PR DESCRIPTION
**Pull request by wwilsman**
## Purpose
I noticed that after the `rescue` block in the configuration controller the method continues execution, causing a double render.

## Approach
- Move the rescue block to the bottom of the method and specifically catch `JSON:ParserError`
- Also rescue `NoMethodError` in the event that the JSON payload does not contain the proper keys
- Add test to make sure we get the proper response code

### CODE REVIEW

**Review by elrickvm — APPROVED** [review]

**Review by sadatay — APPROVED** [review]

**Comment by sadatay** [comment]
when we get more into deserialization i'm guessing we'll end up pulling that parse block out somewhere, but for now this lgtm

**Review by cowboyd — CHANGES_REQUESTED** [review]
The problem here is that we're potentially doing a double-render in the event of an exception.

Can we not remove the `begin` / `rescue` / `end` altogether and move the `rescue` down to the bottom?

**Comment by wwilsman** [comment]
@cowboyd that’s why I added the return. To prevent the double render. If we moved the rescue block to be for the entire method, it might also render the JSON error for an unrelated exception.

**Comment by cowboyd** [comment]
@wwilsman We would still want to render an error though, right? In that case, could we not use a separate `rescue` block for each type of error to render?

**Comment by wwilsman** [comment]
@cowboyd I forgot you can rescue specific exceptions in Ruby. Adjusted.

**Comment by cowboyd** [comment]
Ruby, you're a-ok 👌

**Review by cowboyd — APPROVED** [review]

**Pull request merged**
